#!/bin/bash
#
# Profile GAPBS BFS on a *uniform random* synthetic graph generated by GAPBS itself.
#
# GAPBS supports:
#   -u <scale>   generate uniform random graph with 2^scale vertices
#   -k <degree>  average degree for synthetic graphs (default 16)
#
# This script runs:
#   ./bfs -u $SCALE -k $DEGREE -n $ITERS
# and then collects PEBS data-address samples using perf and produces:
#   - virt_heatmap.png
#   - hot_persistence.png
#
# Example:
#   SCALE=24 ITERS=128 PERF_UNTIL_EXIT=1 SAMPLE_PERIOD=500 HEATMAP_VMAX_PCT=99.0 ./run_gapbs_bfs_uniform_profile.sh
#

# Optional: load sudo password helper if available (used for sysctl tuning)
SCRIPT_LIB_DIR="${SCRIPT_LIB_DIR:-/mnt/nfs/xiayanwen/research/demos/scripts}"
if [ -f "${SCRIPT_LIB_DIR}/password_lib.sh" ]; then
  # shellcheck disable=SC1090
  source "${SCRIPT_LIB_DIR}/password_lib.sh"
  define_user_password
  export SUDO_PASS="${USER_PASSWORD:-}"
fi

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

# ===== Config (override via env) =====
GAPBS_DIR=${GAPBS_DIR:-"/home/xiayanwen/app-case-studies/memtis/memtis-userspace/bench_dir/gapbs"}

# Uniform synthetic graph knobs
SCALE=${SCALE:-24}     # graph has 2^SCALE vertices
DEGREE=${DEGREE:-16}   # average degree (GAPBS uses -k)
ITERS=${ITERS:-64}     # BFS trials (GAPBS uses -n)

# BFS_ARGS can override everything if you want full manual control.
BFS_ARGS=${BFS_ARGS:-"-u ${SCALE} -k ${DEGREE} -n ${ITERS}"}

# For synthetic graph, you usually want to capture graph construction too.
WARMUP_SEC=${WARMUP_SEC:-1}

# Profile settings
PERF_DURATION=${PERF_DURATION:-60}
SAMPLE_PERIOD=${SAMPLE_PERIOD:-1000}  # smaller => higher samples/sec
PERF_UNTIL_EXIT=${PERF_UNTIL_EXIT:-1} # recommended: capture full run

# Analysis params
MAX_POINTS=${MAX_POINTS:-2000000}
HEATMAP_DPI=${HEATMAP_DPI:-300}
HEATMAP_GRIDSIZE=${HEATMAP_GRIDSIZE:-500}
HEATMAP_FIGSIZE=${HEATMAP_FIGSIZE:-"10,6"}
HEATMAP_COLOR_SCALE=${HEATMAP_COLOR_SCALE:-log}      # log|linear
HEATMAP_VMAX_PCT=${HEATMAP_VMAX_PCT:-""}             # e.g. 99.0 (empty=auto)
PERSIST_TOPK=${PERSIST_TOPK:-2048}
PERSIST_REF_WINDOW=${PERSIST_REF_WINDOW:-2}
PERSIST_BIN_SEC=${PERSIST_BIN_SEC:-10}
ADDR_MODE=${ADDR_MODE:-window}        # dominant | window
WINDOW_GB=${WINDOW_GB:-12}
WINDOW_STRATEGY=${WINDOW_STRATEGY:-around}
PLOT_Y_OFFSET=${PLOT_Y_OFFSET:-1}

OUT_DIR=${OUT_DIR:-"$ROOT_DIR/perf_results/gapbs_bfs_uniform_s${SCALE}_k${DEGREE}_n${ITERS}"}
TITLE=${TITLE:-"GAPBS BFS (uniform -u${SCALE} -k${DEGREE})"}

mkdir -p "$OUT_DIR"

# Resolve perf path (override with PERF_BIN=/path/to/perf)
PERF_BIN="${PERF_BIN:-}"
if [ -z "$PERF_BIN" ]; then
  if command -v perf >/dev/null 2>&1; then
    PERF_BIN="$(command -v perf)"
  elif [ -x /usr/local/bin/perf ]; then
    PERF_BIN="/usr/local/bin/perf"
  elif [ -x /usr/lib/linux-hwe-6.8-tools-6.8.0-90/perf ]; then
    PERF_BIN="/usr/lib/linux-hwe-6.8-tools-6.8.0-90/perf"
  else
    echo "ERROR: perf not found. Install linux-tools/perf or set PERF_BIN=/path/to/perf" >&2
    exit 1
  fi
fi

echo "perf: $PERF_BIN"
echo "out:  $OUT_DIR"

if [ -n "${SUDO_PASS:-}" ]; then
  echo "=== Set perf sysctls (no throttling) ==="
  echo "$SUDO_PASS" | sudo -S sh -c '
    echo 100000000 > /proc/sys/kernel/perf_event_max_sample_rate
    echo 0 > /proc/sys/kernel/perf_cpu_time_max_percent
    echo -1 > /proc/sys/kernel/perf_event_paranoid
  ' 2>/dev/null || true
else
  echo "=== Skip sysctl (no sudo password provided) ==="
fi

echo "=== Start GAPBS BFS (uniform synthetic graph) ==="
cd "$GAPBS_DIR"

if [ ! -x "$GAPBS_DIR/bfs" ]; then
  echo "ERROR: GAPBS BFS binary not found: $GAPBS_DIR/bfs" >&2
  echo "Fix: build GAPBS (from GAPBS_DIR):" >&2
  echo "  cd \"$GAPBS_DIR\" && make bfs" >&2
  exit 1
fi

if [ -n "${OMP_NUM_THREADS:-}" ]; then
  export OMP_NUM_THREADS
fi

./bfs $BFS_ARGS >"$OUT_DIR/bfs.log" 2>&1 &
BFS_PID=$!
export BFS_PID
echo "bfs pid: $BFS_PID"

cleanup() {
  kill "$BFS_PID" 2>/dev/null || true
}
trap cleanup INT TERM

sleep "$WARMUP_SEC"

if ! kill -0 "$BFS_PID" 2>/dev/null; then
  echo "ERROR: bfs exited before profiling started; see log: $OUT_DIR/bfs.log" >&2
  tail -n 120 "$OUT_DIR/bfs.log" >&2 || true
  exit 1
fi

echo "=== Snapshot /proc maps (for labeling hot ranges later) ==="
if [ -r "/proc/$BFS_PID/maps" ]; then
  cp "/proc/$BFS_PID/maps" "$OUT_DIR/proc_maps.txt" 2>/dev/null || true
fi
if [ -r "/proc/$BFS_PID/smaps_rollup" ]; then
  cp "/proc/$BFS_PID/smaps_rollup" "$OUT_DIR/smaps_rollup.txt" 2>/dev/null || true
fi

echo "=== Determine address filter range ==="
ADDR_MIN=""
ADDR_MAX=""
# Synthetic graph is in memory; best heuristic is biggest anonymous rw mapping (often where CSR lives)
MAP_RANGE=$(
  python3 - <<'PY'
import re
pid = int(__import__("os").environ["BFS_PID"])
best = ""
best_sz = -1
with open(f"/proc/{pid}/maps", "r", encoding="utf-8", errors="ignore") as f:
    for line in f:
        # Example:
        # 7f0b2c000000-7f0b2d000000 rw-p 00000000 00:00 0
        parts = line.split()
        if len(parts) < 5:
            continue
        addr = parts[0]
        perms = parts[1]
        path = parts[5] if len(parts) >= 6 else ""
        if "r" not in perms or "w" not in perms:
            continue
        if path not in ("", "0"):
            continue
        m = re.match(r"^([0-9a-fA-F]+)-([0-9a-fA-F]+)$", addr)
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16)
        sz = hi - lo
        if sz > best_sz:
            best_sz = sz
            best = addr
print(best)
PY
)
if [ -n "$MAP_RANGE" ]; then
  ADDR_MIN="0x${MAP_RANGE%-*}"
  ADDR_MAX="0x${MAP_RANGE#*-}"
  echo "Using anon-rw mapping: $ADDR_MIN - $ADDR_MAX"
else
  echo "No /proc maps range found; will auto-infer from samples."
fi

echo "=== perf record (PEBS data addr) ==="
PERF_DATA="$OUT_DIR/perf.data"
rm -f "$PERF_DATA" 2>/dev/null || true

if [ "$PERF_UNTIL_EXIT" = "1" ]; then
  echo "Sampling mode: until bfs exits (PERF_UNTIL_EXIT=1)"
  "$PERF_BIN" record \
    -e '{cpu/mem-loads-aux/,cpu/mem-loads/pp}:S' \
    -c "$SAMPLE_PERIOD" \
    -p "$BFS_PID" \
    -d \
    --no-buildid --no-buildid-cache \
    -o "$PERF_DATA" \
    -- sleep 9999999 >/dev/null 2>&1 &
  PERF_REC_PID=$!
  wait "$BFS_PID" 2>/dev/null || true
  kill -INT "$PERF_REC_PID" 2>/dev/null || true
  wait "$PERF_REC_PID" 2>/dev/null || true
else
  echo "Sampling mode: fixed duration ${PERF_DURATION}s"
  "$PERF_BIN" record \
    -e '{cpu/mem-loads-aux/,cpu/mem-loads/pp}:S' \
    -c "$SAMPLE_PERIOD" \
    -p "$BFS_PID" \
    -d \
    --no-buildid --no-buildid-cache \
    -o "$PERF_DATA" \
    -- sleep "$PERF_DURATION" 2>&1 | tail -n 5
fi

if [ ! -s "$PERF_DATA" ]; then
  echo "ERROR: perf did not produce perf.data (or it is empty): $PERF_DATA" >&2
  echo "See BFS log: $OUT_DIR/bfs.log" >&2
  exit 1
fi

echo "=== Extract points (time,event,addr) ==="
cd "$ROOT_DIR"
POINTS_TXT="$OUT_DIR/bfs_points.txt"
rm -f "$POINTS_TXT" 2>/dev/null || true
"$PERF_BIN" script -i "$PERF_DATA" -F time,event,addr 2>/dev/null > "$POINTS_TXT"

if [ ! -s "$POINTS_TXT" ]; then
  echo "ERROR: no samples decoded into points file: $POINTS_TXT" >&2
  exit 1
fi

echo "=== Plot heatmap ==="
if [ -z "$ADDR_MIN" ] || [ -z "$ADDR_MAX" ]; then
  read -r ADDR_MIN ADDR_MAX _CNT < <(
    python3 ./infer_addr_range.py --mode "$ADDR_MODE" --window-gb "$WINDOW_GB" --window-strategy "$WINDOW_STRATEGY" --max-lines 200000 < "$POINTS_TXT"
  )
  echo "Inferred addr range ($ADDR_MODE): $ADDR_MIN - $ADDR_MAX"
fi

PLOT_ARGS=(--input "$POINTS_TXT" --output "$OUT_DIR/virt_heatmap.png" --title "$TITLE" --addr-min "$ADDR_MIN" --addr-max "$ADDR_MAX" --max-points "$MAX_POINTS" --dpi "$HEATMAP_DPI" --gridsize "$HEATMAP_GRIDSIZE" --figsize "$HEATMAP_FIGSIZE" --color-scale "$HEATMAP_COLOR_SCALE")
if [ -n "$HEATMAP_VMAX_PCT" ]; then
  PLOT_ARGS+=(--vmax-percentile "$HEATMAP_VMAX_PCT")
fi
if [ "$PLOT_Y_OFFSET" = "1" ]; then
  PLOT_ARGS+=(--y-offset --ylabel "Virtual address (offset)")
else
  PLOT_ARGS+=(--ylabel "Virtual address")
fi
python3 ./plot_phys_addr.py "${PLOT_ARGS[@]}"

echo "=== Plot hot persistence ==="
python3 ./hot_persistence.py \
  --input "$POINTS_TXT" \
  --output "$OUT_DIR/hot_persistence.png" \
  --title "${TITLE} hot persistence" \
  --addr-min "$ADDR_MIN" --addr-max "$ADDR_MAX" \
  --ref-start 0 --ref-window "$PERSIST_REF_WINDOW" \
  --topk "$PERSIST_TOPK" \
  --bin "$PERSIST_BIN_SEC"

echo ""
echo "Done:"
echo "  perf.data:         $PERF_DATA"
echo "  points:            $POINTS_TXT"
echo "  heatmap:           $OUT_DIR/virt_heatmap.png"
echo "  hot persistence:   $OUT_DIR/hot_persistence.png"
echo "  bfs log:           $OUT_DIR/bfs.log"


